[package]
name = "purple"
version = "0.0.1-placeholder"
authors = ["jaynus <jaynus@gmail.com>"]
edition = "2018"
description = "placeholder for a library"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
