[package]
name = "purple"
version = "0.0.1-placeholder"
authors = ["jaynus <jaynus@gmail.com>"]
edition = "2018"
description = "placeholder for a library"
license = "MIT"

[features]

[dependencies]

[dev-dependencies]
criterion = "0.3"
rayon = "1.2"